# Generated by Django 5.2.2 on 2025-06-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="gateway_reference",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_gateway",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
